theme: jekyll-theme-slate
title: Welcome to the Octocat's homepage!
description: feel free to bookmark this to keep an eye on my project updates
title: Cayman theme

description: Cayman is a clean, responsive theme for GitHub Pages.

show_downloads: true

google_analytics:

theme: jekyll-theme-cayman
